### ISSUE TITLE
Error in Swipe action

### ISSUE THREAD

**Issue by SaniokUA** [wdullaer/SwipeActionAdapter#34]
I add SwipeActionAdapter and implements SwipeActionListener. 

![i45h93i](https://cloud.githubusercontent.com/assets/7628034/9783374/7dd0d05a-57ac-11e5-915d-98e6da72119d.png)

When i swipe listView's element hasAction method runs and i have error 

![sax12qu](https://cloud.githubusercontent.com/assets/7628034/9783489/427ed668-57ad-11e5-8e57-ba55027d92a8.png)

My adapter 

![qro31nb](https://cloud.githubusercontent.com/assets/7628034/9783510/6ff1baf2-57ad-11e5-89eb-0ca974bb9e11.png)

**Comment by SaniokUA** [comment]
I use <ListView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/listMain"
        />

**Comment by SaniokUA** [comment]
ActionBarActivity its a problem. When i extending from Activity all works

**Comment by wdullaer** [comment]
Without proper instructions to reliably reproduce this issue, I have to consider this to be a bug in your code rather than the library.

I suggest you use the debugger to step through the code and find out where the NullPointerException is coming from.
Also try using AppCompatActivity rather than ActionBarActivity.

**Comment by SaniokUA** [comment]
AppCompatActivity can't resolve my problem. Only extending from Activity or deleting LoaderManager.LoaderCallbacks<Cursor> helps me.

**Comment by wdullaer** [comment]
This still sounds like an issue with your code, rather than this library.
If you can make a sample project that reproduces the issue, I'll take a look at it.

Until then, I suggest you whip out the debugger and step through your code to see what's happening. Your description sounds like it's some sort of race condition.

**Comment by hussamabd** [comment]
i have the same issue here , and change to Activity didn't solve my problem

**Comment by hussamabd** [comment]
i discovered the issue , this issue appear only when you try to set swipe adapter with empty list view , so in this situation and i think that exception raised because the onswip event invoked on not exist item view in list view .
sorry bad english
