### ISSUE TITLE
Mixed list

### ISSUE THREAD

**Issue by CyberNyanta** [wdullaer/SwipeActionAdapter#56]
Can I create list where items can have different background?

**Comment by wdullaer** [comment]
Your items can have any background they like. This adapter just wraps around them.
The backgrounds of the "swiped" backgrounds cannot be changed a per item level, but the which background the items show by default is entirely up to your implementation

**Comment by CyberNyanta** [comment]
Can your library be customized in this way? If you interested I'm doing TodoList application now, for completed and uncompleted task I have different swipe backgrounds, this is not problem because they located in different lists. But I want to create search with both types, with saved swipe actions, like made in `https://play.google.com/store/apps/details?id=com.todoist&hl=en` application.
If such behavior is possible to make I could contribute it to your project.

**Comment by wdullaer** [comment]
You could use this library as a starting point to build something like that, but it can't just be added onto it.

In order for this to work, the `SwipeActionAdapter` will need to know the state of the underlying item it is wrapping (in this case it's completed state). This can't be solved generically, because that state is application specific.
Right now the adapter makes no assumptions on what the underlying adapter is doing, keeping it generically applicable.
